### PR TITLE
fix: randomise rocket positions

### LINKED ISSUE #25: 🚀 Rocket Positioning
Shh, don't tell everyone, but you can actually jump over the highest rockets.

Should a 4th, higher rocket be introduced to mean that you _have_ to duck at some points?

The code change is easy enough: extend the `FLYER_HEIGHTS` list in `constants.py`.

### PR DESCRIPTION
**Pull request by PsypherPunk**
replace the fixed positions of the rockets with a random range, between half-a-duck-below-the-clouds and half-a-duck height.

fixes #25

### CODE REVIEW

**Review by gvee-uk — APPROVED** [review]
I was a bit worried this would make things too difficult, but actually it makes it pretty interesting, IMO.

**Comment by gvee-uk** [comment]
Hmmm...

Few more plays and now I'm thinking that I don't have to duck nearly as much, which is a bit of a shame (as I like the animation 😁)

**Comment by PsypherPunk** [comment]
Agreed. However, previously, if you could duck under it, you could jump over it. So at high speed, it just became a matter of timing your jumps.

With this, it's a matter of knowing when *not* to jump at high speed.

Could do some more work to figure out if there's an appropriate sweet spot that you can't jump over and must duck under...?

**Comment by gvee-uk** [comment]
Fair points!

> Could do some more work to figure out if there's an appropriate sweet spot that you can't jump over and must duck under...?

Unfortunately I don't think there is a spot for this given the asset sizing (based on previous tinkering), so I wouldn't bother spending any time on it 👌

**Pull request merged**
